import Link from 'next/link'
import {signIn, useSession} from 'next-auth/client'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Button from '@mui/material/Button';
import LinearProgress from '@mui/material/LinearProgress';
import Checkbox from '@mui/material/Checkbox';



export default function SignIn() {

    const [session, loading] = useSession()
    const router = useRouter()
    const label = { inputProps: { 'aria-label': 'Checkbox demo' } };


    useEffect(() => {
      if (session) {
        router.push('/userpage')
      }
    }, [session, router])

    function signInFunction() {
        signIn('google')
        if (loading) {
            return <div className='grid justify-center pt-24'><LinearProgress /></div> 
        }
    }
    
    if (loading) {
        return (
            <>
            <div className='grid justify-center pt-24'><LinearProgress /></div>          
            </>
        )
    } else {
        return (
        <>
            <Head>
                <title>Samplified</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/head-logo.png" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet"></link>
            </Head>
            <div 
            style={
                {
                  fontFamily: `'Ubuntu', sans-serif`
          
                }
              }
            >  
                <div className="position absolute top-3 right-8 font-bold text-white">
                    <Link href="/">X</Link>
                </div> 
                {/* mobile sign in */}
                <div className='text-white visible lg:invisible'>
                    <div
                    className='w-full h-full absolute top-1/2 transform -translate-y-1/2'
                    style={
                        {
                            backgroundImage: `url(/bg-image.svg)`,
                            backgroundSize: "630px 1152px"
                        }
                    }
                    >
                        <div className='grid justify-center mt-32 text-center'>
                            <img 
                                className="mx-auto h-12 w-auto lg-logo pb-10" 
                                src="/logo-large.svg" 
                                alt="Workflow" 
                                />
                            <div className='pb-10 grid text-center'>
                            <h2 className="text-2xl">Sign in to Samplified</h2>
                            <h5 className='text-center text-gwhite opacity-30'>Enter your details below</h5>
                            </div>
                            
                            <a className='border mx-12 rounded-full cursor-pointer h-10' type="button" onClick={() => signInFunction()}>
                                <Button className='border'>
                                    <img className='mt-1' src="/ic_google.svg" alt="Sign in with Google"></img>
                                </Button>
                            </a>

                            <div className='flex pt-10 justify-center'>
                                <p className='divider-horizontal-solid-2 mt-2.5'></p>
                                <p className='or'>
                                    OR
                                </p>
                                <p className='divider-horizontal-solid-1-2 mt-2.5'></p>
                            </div>

                            <div className='pt-10'>
                                <form className='relative grid justify-center'>
                                    <label className='bg-theme left-3'><p className="label-text">Email Address</p></label>
                                    <input className='border border-gwhite rounded-md bg-theme h-14 pl-3' type="email" placeholder="your@email.com" />
                                    
                                    <input className='border border-gwhite rounded-md bg-theme h-14 mt-5 pl-3' type="password" placeholder='Password' />

                                    <div className='flex justify-between mt-5'>
                                    <a className='flex justify-between'>
                                        <Checkbox {...label}/>
                                        <p>Remember Me</p>
                                    </a>
                                    <Link href="/forgot"><a className='forgot'>Forgot Password?</a></Link>
                                    </div>

                                    <button className='sign-in-button-2 mt-10'>
                                        Sign In
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>

                </div>

                {/* Sign in */}
                <div className="grid grid-cols-4 gap-4 invisible lg:visible">
                    <div className="col-span-2">
                        <div className='relative'>
                            <img 
                            src='/BG.svg' 
                            alt="background"
                            className='bg-sign'
                            ></img>

                            <div className='absolute top-1/2 transform -translate-y-1/2 left-3'>
                                <a className='hover:bg-opacity-30 hover:cursor-pointer'>
                                <img 
                                className="mx-auto h-12 w-auto main-bg" 
                                src="/main-login.png" 
                                alt="Workflow"
                                />
                                </a>
                            </div>
                            <div className='absolute top-1/2 transform -translate-y-1/2 left-7'>
                                <Link href="/">
                                    <a className='hover:bg-opacity-30 hover:cursor-pointer'>
                                    <img 
                                    className="mx-auto h-12 w-auto lg-logo" 
                                    src="/logo-large.svg" 
                                    alt="Workflow" 
                                    /></a>
                                </Link>
                            </div>
                        </div>
                    </div>
                    <div className='col-span-4 lg:col-span-2 relative text-white'>
                        <div
                        className='w-full h-full absolute left-0 top-0'
                        style={
                            {
                                backgroundImage: `url(/bg-image.svg)`,
                                backgroundSize: "630px 1152px"
                            }
                        }
                        >
                            <div className='absolute top-1/2 transform -translate-y-1/2 remove-w'>
                                <div className='pb-10'>
                                <h2 className="sign-in-to-samplified">Sign in to Samplified</h2>
                                <h5 className='details'>Enter your details below</h5>
                                </div>
                                
                                <a className='google grid justify-center cursor-pointer remove-w' type="button" onClick={() => signInFunction()}>
                                    <Button>
                                        <img className='' src="/ic_google.svg" alt="Sign in with Google"></img>
                                    </Button>
                                </a>

                                <div className='flex pt-10'>
                                    <p className='divider-horizontal-solid mt-2.5'></p>
                                    <p className='or'>
                                        OR
                                    </p>
                                    <p className='divider-horizontal-solid-1 mt-2.5'></p>
                                </div>

                                <div className='pt-10'>
                                    <form className='relative w-96'>
                                        <label className='label absolute bottom-60 mb-1 bg-theme left-3 remove-w'><p className="label-text">Email Address</p></label>
                                        <input className='sign-input pl-3 remove-w' type="email" placeholder="your@email.com" />
                                        
                                        <input className='sign-input mt-5 pl-3 remove-w' type="password" placeholder='Password' />

                                        <div className='forgot-password flex justify-between mt-5 remove-w'>
                                        <a className='flex justify-between'>
                                            <Checkbox {...label}/>
                                            <p>Remember Me</p>
                                        </a>
                                        <Link href="/forgot"><a className='forgot'>Forgot Password?</a></Link>
                                        </div>

                                        <button className='sign-in-button mt-10 remove-w'>
                                            Sign In
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </>

        )
    }
}