import Head from 'next/head'
import Image from 'next/image'
import Navigator from '../components/navigator'
import Footer from '../components/footer'
import Container from '@mui/material/Container';
import Link from 'next/link'
import Button from '@mui/material/Button';
import { getSession, useSession } from 'next-auth/client'






export default function Home() {
  const [session, loading] = useSession()
  
  return (
    <div>
      <Head>
        <title>Samplified</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/main.jpg" />
      </Head>
      
      <Navigator />

    <main>

      <div className='relative'>
        <img //eslint-disable-line
          style={{
            width: '100%'
          }}
          className="h-96 sm:h-screen"
          layout='fill' 
          src="https://creativetechlab.com/wp-content/uploads/2016/08/music-producer-disconnected-1280x640.jpg" 
          alt='main'></img>
          <div
          className='absolute top-12 right-10 left-10 sm:top-1/4 sm:left-24 sm:right-1/4 lg:right-1/3 xl:right-1/2 md:top-1/4 md:left-1/4 flex bg-black bg-opacity-40 bg-cover rounded-xl text-white text-lg text-left font-bold'
          >
            <div className='py-5 px-10 max-w-lg'>
              <a className='py-1 font-extrabold font text-3xl sm:text-5xl'>
              Samplified
              </a><br></br><br></br>
              <p className='text-sm sm:text-2xl'>
              Samplified is the industrys highest quality,
              open source sample library. Get access to millions offset
              sounds made by producers, and sound designers—all
              available at your fingertips.
              </p><br></br>
              {session ?
              <Button className='bg-gray-800 text-white text-sm'><Link href="/userpage">Go to your Profile</Link></Button>
              :
              <Button className='bg-gray-800 text-white text-sm'><Link href="/sign-up">Sign up Now</Link></Button>
              }
            </div>
          </div>
      </div>
      <div>
        <Container maxWidth="md">
          <div className='py-24 flex flex-wrap md:flex-nowrap justify-between'>
            <div className='py-5'>
              <a className='py-1 font-extrabold font text-3xl'>
              Find that sound
              in your head
              </a><br></br><br></br>
              <p>
              Samplified is the industrys highest quality,
              open source sample library. Get access to millions offset
              sounds made by producers, and sound designers—all
              available at your fingertips.
              </p><br></br>
              <a className='py-8'>
              <Link href="/sounds"><Button variant='contained' className='bg-gray'>Click Here</Button></Link>
              </a>
            </div>
            <div className='lg:pl-8 md:pl-0 sm:pl-0'>
            <img src="https://www.image-line.com/wp-content/uploads/2020/11/fl-studio-UI.png" alt="DAW"></img>
            </div>
          
          </div>
        </Container>

      </div>

      <div className='py-10 bg-gray-800 grid justify-center text-white'>
        <p>
          something fun here
        </p>
      </div>

      <div>
        <Container maxWidth="md">
        <div className='py-10 font-extrabold font text-3xl grid justify-center'>
          <p className='text-center'>
            What peeps say about stuff
          </p>
        </div>

          <div className='pb-10 flex flex-wrap md:flex-nowrap justify-center md:justify-between'>

          <div className='lg:pl-8 md:pl-2 sm:pl-0 py-3'>
            <img 
            className="rounded-full h-44 w-full"
            src="https://t4.ftcdn.net/jpg/03/83/25/83/360_F_383258331_D8imaEMl8Q3lf7EKU2Pi78Cn0R7KkW9o.jpg" alt="DAW"></img>
            <div className='font-extrabold font text-1xl grid justify-center'>
              <p>
                Josh probably
              </p>
            </div>
            <p className='text-center'>Something something something darkside</p>
            </div>
            <div className='lg:pl-8 md:pl-2 sm:pl-0 py-3'>
            <img 
            className="rounded-full h-44 w-full"
            src="https://img.favpng.com/19/6/14/stock-photography-royalty-free-person-png-favpng-DZGTnmn1uqimHihD8vgVJMRFG.jpg" alt="DAW"></img>
            <div className='font-extrabold font text-1xl grid justify-center'>
              <p>
                Josh probably
              </p>
            </div>
            <p className='text-center'>Something something something darkside</p>
            </div>
            <div className='lg:pl-8 md:pl-2 sm:pl-0 py-3'>
            <img 
            className="rounded-full h-44 w-full"
            src="https://d32ijn7u0aqfv4.cloudfront.net/wp/wp-content/uploads/20190130110644/man-cafe-newspaper_SOIN18127_586670_st_780x440.jpg" alt="DAW"></img>
            <div className='font-extrabold font text-1xl grid justify-center'>
              <p>
                Josh probably
              </p>
            </div>
            <p className='text-center'>Something something something darkside</p>
            </div>
          
          </div>
        </Container>

      </div>
      </main>
    <Footer />
    </div>
  )
}
