import Head from 'next/head'
import Image from 'next/image'
import Navigator from '../components/navigator'
import Footer from '../components/footer'
import Container from '@mui/material/Container';
import Link from 'next/link'
import Button from '@mui/material/Button';





export default function Home() {
  return (
    <div>
      <Head>
        <title>Samplified</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/main.jpg" />
      </Head>
      
      <Navigator />

      <main>
        <div className="bg-[url('/main.jpg')]"></div>
      <img //eslint-disable-line
      style={{
        width: '100%'
      }}
      layout='fill' 
      src="https://creativetechlab.com/wp-content/uploads/2016/08/music-producer-disconnected-1280x640.jpg" 
      alt='main'></img>

      <div>
        <Container maxWidth="md">
          <div className='py-24 flex flex-row justify-between'>
            <div className=''>
              <a className='py-1 font-extrabold font text-3xl'>
              Find that sound
              in your head
              </a><br></br><br></br>
              <p>
              Samplified is the industrys highest quality,
              open source sample library. Get access to millions offset
              sounds made by producers, and sound designers—all
              available at your fingertips.
              </p><br></br>
              <a className='py-8'>
              <Link href="/sounds"><Button variant='contained' className='bg-gray'>Click Here</Button></Link>
              </a>
            </div>
            <div className='pl-8'>
            <img src="https://www.image-line.com/wp-content/uploads/2020/11/fl-studio-UI.png" alt="DAW"></img>
            </div>
          
          </div>
        </Container>

      </div>
      </main>
    <Footer />
    </div>
  )
}
