import Head from 'next/head'
import Image from 'next/image'
import Navigator from '../components/navigator'
import Footer from '../components/footer'
import Container from '@mui/material/Container';
import Link from 'next/link'
import Button from '@mui/material/Button';
import { getSession, useSession } from 'next-auth/client'






export default function Home() {
  const [session, loading] = useSession()
  
  return (
    <div>
      <Head>
        <title>Samplified</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/head-logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet"></link>
      </Head>
      

    <main 
    style={
      {
        fontFamily: `'Ubuntu', sans-serif;`

      }
    }
    
    >
      <div className='relative w-full h-full'>

        <img //eslint-disable-line
          style={
            {
              height: "700px"
            }
          }
          className="w-full h-screen sm:w-full main-photo"
          src="main.png" 
          alt='main'
          ></img>
          <div
          className='flex flex-wrap w-3/4 text-white text-center sm:text-left font-bold'
          >
            <div className="absolute top-0 w-full">
            <Navigator/>
            </div>
            <div className='py-5 px-10 max-w-lg absolute top-44 md:left-24'>

              <div>
                <a className='find-your-sound uppercase'>
                Find your sound  
                </a><br></br><br></br>
                <p className='samplified-is-the-in'>
                Samplified is the industrys highest quality,
                open source sample library. Get access to millions offset
                sounds made by producers, and sound designers—all
                available at your fingertips.
                </p><br></br>
                {session ?
                <button className='button-color text-white text-sm'><Link href="/userpage" className="get-access">Go to your Profile</Link></button>
                :
                <button className='button-color text-white text-sm'><Link href="/sign-up" className="get-access">Get Access</Link></button>
                }
              </div>
            </div>
            <div className='absolute bottom-96 diag w-full h-36 invisible md:visible'>
              
            </div>
            <div className='absolute right-44 sm:right-0 sm:h-44 top-80 invisible lg:visible'>
                  <img className="fl-pic" src="/fl.svg" alt="DAW"></img>
            </div>

          </div>

          <div className='pt-28 pb-20 bg-theme flex flex-wrap md:flex-nowrap justify-center md:justify-evenly'>

            <div className='lg:pl-8 md:pl-2 sm:pl-0 py-3 text-box text-center'>
              <div className='grid pb-4 justify-center'>
              <img 
              className="shapes"
              src="1.svg" alt="DAW"></img>
              </div>

              <div className='feature text-center'>
                  Feature 1
              </div>
              <p className='text-center boxes-text'>Photographs are a way of preserving a moment in our lives for the rest of our lives. Many of us have at least been tempted at the flashy array of photo printers which seemingly leap off the shelves at even the least tech-savvy.</p>
            </div>
            <div className='lg:pl-8 md:pl-2 sm:pl-0 py-3 text-box'>
              <div className='grid pb-4 justify-center'>
                <img 
                className="shapes"
                src="2.svg" alt="DAW"></img>
              </div>
              <div className='feature text-center'>
                  Feature 2
              </div>
              <p className='text-center boxes-text'>Photographs are a way of preserving a moment in our lives for the rest of our lives. Many of us have at least been tempted at the flashy array of photo printers which seemingly leap off the shelves at even the least tech-savvy.</p>
            </div>
            <div className='lg:pl-8 md:pl-2 sm:pl-0 py-3 text-box'>
              <div className='grid pb-4 justify-center'>
                  <img 
                  className="shapes"
                  src="3.svg" alt="DAW"></img>
              </div>
              <div className='feature text-center'>
                  Feature 3
              </div>
              <p className='text-center boxes-text'>Photographs are a way of preserving a moment in our lives for the rest of our lives. Many of us have at least been tempted at the flashy array of photo printers which seemingly leap off the shelves at even the least tech-savvy.</p>
            </div>

          </div>

      </div>


      </main>
    {/* <Footer /> */}
    </div>
  )
}
