import Navigator from '../../components/navigator'
import Footer from '../../components/footer'
import dbInfo from '../api/db/getSound';
import Search from '../../components/search'
import Head from 'next/head'

export default function AllSounds({ allSounds }) {

    return (
        <div className='bg-theme' 
        style={
            {
                backgroundImage: `url(/main.png)`,
                fontFamily: `'Ubuntu', sans-serif`
            }
        }
        >
        <Head>
            <title>Samplified</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/head-logo.png" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet"></link>
        </Head>
        <Navigator />
            <div className='bg-theme'>
            <Search allSounds={allSounds}/>
            </div>
        </div>
    )
}

AllSounds.defaultProps = {
    props: [],
  }
  
  export async function getServerSideProps(ctx) {
  
      const props = { }
      const allSounds = await dbInfo()
   
      return {
          props: { allSounds },
      }
  }